// Source: https://www.studiobinder.com/blog/movie-genres-list/
export const genres = [
    // "Action",
    "Heroic Bloodshed",
    "Military Action",
    "Espionage",
    "Wuxia Action",
    "Disaster",
    "Adventure",
    "Superhero",

    // "Animation",
    "Traditional Animation",
    "Stop Motion",
    "Claymation",
    "Cutout Animation",
    "Computer Generated Imagery",
    "Puppetry",
    "Live-Action Animation",

    // "Comedy",
    "Action-Comedy",
    "Dark Comedy",
    "Romantic Comedy",
    "Buddy Comedy",
    "Road Comedy",
    "Slapstick Comedy",
    "Parody",
    "Spoof",
    "Satire",
    "Sitcom",
    "Sketch Comedy",
    "Mockumentary",
    "Prank",

    // "Crime",
    "Caper",
    "Heist",
    "Gangster",
    "Cop",
    "Detective",
    "Courtroom",
    "Procedural",

    // "Drama",
    "Melodrama",
    "Teen Drama",
    "Philosophical Drama",
    "Medical Drama",
    "Legal Drama",
    "Political Drama",
    "Anthropological Drama",
    "Religious Drama",
    "Docudrama",

    // "Experimental",
    "Surrealist",
    "Absurdist",

    // "Fantasy",
    "Contemporary Fantasy",
    "Urban Fantasy",
    "Dark Fantasy",
    "High Fantasy",
    "Myth",

    // "Historical",
    "Historical Event",
    "Biography",
    "Historical Epic",
    "Historical Fiction",
    "Period Piece",
    "Alternate History",

    // "Horror",
    "Ghost",
    "Monster",
    "Werewolf",
    "Vampire",
    "Occult",
    "Slasher",
    "Splatter",
    "Found Footage",
    "Zombie",

    // "Romance",
    "Romance Drama",
    "Romance Thriller",
    "Period Romance",

    // "Science Fiction",
    "Post-Apocalyptic",
    "Utopian",
    "Dystopian",
    "Cyberpunk",
    "Steampunk",
    "Tech Noir",
    "Space Opera",
    "Contemporary Science Fiction",
    "Military",

    // "Thriller",
    "Psychological Thriller",
    "Mystery",
    "Techno-Thriller",
    "Film Noir",

    // "Western",
    "Epic Western",
    "Empire Western",
    "Marshal Western",
    "Outlaw Western",
    "Revenge Western",
    "Revisionist Western",
    "Spaghetti Western",

    "Musical",
    "War",
    "Biopic",
]